### ISSUE TITLE
Errors: (Warning: Unexpected server response, key 'version' is '1.9', not '2.0'.)

### ISSUE THREAD

**Issue by manish-cr** [customautosys/wasg-register-gui#1]
I encountered the error mentioned in the title while using the wireless@sgx GUI on Linux Mint Cinnamon. Any solutions?

**Comment by customautosys** [comment]
![wasg-register-gui 1](https://github.com/customautosys/wasg-register-gui/assets/14951259/3e3cffb5-e121-4fc4-99d5-86b4ac9a28f1)
![wasg-register-gui 2](https://github.com/customautosys/wasg-register-gui/assets/14951259/da013045-14cc-45df-bb5d-72f106144d34)

Hi @manish-cr, I think no need to fix as it still works to retrieve the user ID and password. Just ignore the warning.
